name: Parallel Cypress Tests

on: [push]

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          group: 'Actions example'
        env:          
          CYPRESS_RECORD_KEY: 7f853bed-6671-4180-a1b7-bb2f2339b289
          GITHUB_TOKEN: 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